unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 200

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 2000
set-option -g focus-events on

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind-key -r i run-shell "tmux neww sh ~/.local/scripts/tmux-cht.sh"

unbind -T copy-mode-vi MouseDragEnd1Pane

set-option -g status-position top
set -g status-bg default
set -g status-style bg=default

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #{?window_activity_flag, #[fg=colour231]#[blink],#[fg=colour245]}#{?window_bell_flag,#[fg=colour01]#[blink],#[fg=colour245]} #W "
set -g @catppuccin_window_current_text " #{?window_activity_flag, #[fg=colour231]#[blink],#[fg=colour245]}#{?window_bell_flag,#[fg=colour01]#[blink],#[fg=colour245]} #W "
set -g @catppuccin_window_text " #{?window_activity_flag, #[fg=colour231]#[blink],#[fg=colour245]}#{?window_bell_flag,#[fg=colour01]#[blink],#[fg=colour245]} #W "

# run '~/.tmux/plugins/tmux/catppuccin.tmux'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
# set -g status-right ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_session}"


# set -g window-status-format " #{?window_activity_flag, #[fg=colour231]#[blink],#[fg=colour245]}#{?window_bell_flag,#[fg=colour01]#[blink],#[fg=colour245]} #W "
set -g window-status-style 'bg=colour148'
set -g window-status-activity-style 'bg=colour148,fg=colour247,blink'
set -g window-status-bell-style 'bg=colour148,fg=colour01,blink'
set -g window-status-current-style 'bg=colour148,fg=colour09'
set -g monitor-activity on
set -g window-status-activity-style 'blink'
set -g window-status-bell-style 'blink'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @ressurect-strategy-nvim 'session'

# bootstrap tpm
# if "test ! -d ~/.tmux/plugins/tpm" \
#    "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
